### GET request to list all products

GET http://localhost:8080/products

### GET request to list categories

GET http://localhost:8080/categories

### GET request to list products by category (MEN)

GET http://localhost:8080/categories/MEN/products

### GET request to list products by category (BOY)

GET http://localhost:8080/categories/BOY/products