### Récupérer la liste de tous les produits
GET http://localhost:8090/products

### Récupérer la liste des catégories
GET http://localhost:8090/categories

### Récupérer les produits d'une catégorie (MEN)
GET http://localhost:8090/categories/MEN/products

### Récupérer les produits d'une catégorie (BOY)
GET http://localhost:8090/categories/BOY/products

### Créer un nouveau panier sans utilisateur
POST http://localhost:8090/carts
Content-Type: application/json

{
  "userId": null
}

### Créer un nouveau panier pour un utilisateur
POST http://localhost:8090/carts
Content-Type: application/json

{
  "userId": 1
}

### Ajouter un produit à un panier existant
POST http://localhost:8090/carts/1/products
Content-Type: application/json

{
  "productId": 1,
  "quantity": 2,
  "userId": null
}

### Ajouter un produit à un panier existant
POST http://localhost:8090/carts/1/products
Content-Type: application/json

{
  "productId": 2,
  "quantity": 4,
  "userId": null
}

### Mettre à jour la quantité d'un produit dans un panier
PUT http://localhost:8090/carts/1/products/1
Content-Type: application/json

{
  "quantity": 30
}

### Supprimer un produit d'un panier
DELETE http://localhost:8090/carts/1/products/1

### Supprimer un produit d'un panier
DELETE http://localhost:8090/carts/1/products/2

### Récupérer un panier par son ID
GET http://localhost:8090/carts/1

